POST http://localhost:5000/users/oauth/google
Content-Type: application/json

{
    "access_token": "ya29.a0AfH6SMA1_xEgFfo9eGfwNGhLS7dPZUcbsCWXTe8tbW1C7uI1PfidMN1OSO72yrn9L08kZDzbp0tFKY22ROjy8A2wf4ytKJSVePmb9qck6VNPZx9MLRLVoAqLUQwo3AYBJ9c67kNP8LRRf_lQ3xtgygO1N36HVt84dJQ"
}

###

GET http://localhost:5000/users/secret
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYXJ2YWd5YSIsInN1YiI6IjVmMjNkZTcxNTQxOTM5ODNiOWUyYTc5YiIsImlhdCI6MTU5NjM1NTYxNzg5NH0.CY-tVFAJRsVRc1JEg5ZINnNIFdwHE-T2mb_eAtN7ZBw

###

POST http://localhost:5000/trips/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYXJ2YWd5YSIsInN1YiI6IjVmMjNkZTcxNTQxOTM5ODNiOWUyYTc5YiIsImlhdCI6MTU5NjM1NTYxNzg5NH0.CY-tVFAJRsVRc1JEg5ZINnNIFdwHE-T2mb_eAtN7ZBw

###

POST http://localhost:5000/tripRequests/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJTYXJ2YWd5YSIsInN1YiI6IjVmMjNkZTcxNTQxOTM5ODNiOWUyYTc5YiIsImlhdCI6MTU5NjM1NTYxNzg5NH0.CY-tVFAJRsVRc1JEg5ZINnNIFdwHE-T2mb_eAtN7ZBw